[package]
name = "flappy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tilde ~ means favor version 0.8, but if there are bugs in 0.8.1, feel free to get 0.8.x where safe
bracket-lib = "~0.8.1"
